version: "3"

services:
  nemod0:
    image: local:nemo-network
    entrypoint:
      - cosmovisor
      - run
      - start
      - --log_level
      # Note that only this validator has a log-level of `info`; other validators use `error` by default.
      # Change to `debug` for more verbose log-level.
      - info
      - --home
      - /nemo-network/chain/.alice
      - --p2p.persistent_peers
      - "17e5e45691f0d01449c84fd4ae87279578cdd7ec@nemod0:26656,b69182310be02559483e42c77b7b104352713166@nemod1:26656,47539956aaa8e624e0f1d926040e54908ad0eb44@nemod2:26656,5882428984d83b03d0c907c1f0af343534987052@nemod3:26656"
      - --bridge-daemon-eth-rpc-endpoint
      - "${ETH_RPC_ENDPOINT}"
      - --dd-error-tracking-format
      - "true"
      - --max-daemon-unhealthy-seconds
      - "4294967295" # Effectively disable the daemon monitor because bridge daemon is flaky in localnet.
      - --grpc-streaming-enabled
      - "true"
    environment:
      # See https://docs.datadoghq.com/profiler/enabling/go/ for DD_ specific environment variables
      - DD_ENV=localnet_${USER}
      - DD_AGENT_HOST=datadog-agent
      - DAEMON_HOME=/nemo-network/chain/.alice
    volumes:
      - ./localnet/nemo-network0:/nemo-network/chain/.alice/data
    ports:
      - "26657:26657"
      - "9090:9090"
      - "9092:9092" # full node streaming
      - "1317:1317"

  nemod1:
    image: local:nemo-network
    entrypoint:
       - cosmovisor
       - run
       - start
       - --log_level
       - error
       - --home
       - /nemo-network/chain/.bob
       - --p2p.persistent_peers
       - "17e5e45691f0d01449c84fd4ae87279578cdd7ec@nemod0:26656,b69182310be02559483e42c77b7b104352713166@nemod1:26656,47539956aaa8e624e0f1d926040e54908ad0eb44@nemod2:26656,5882428984d83b03d0c907c1f0af343534987052@nemod3:26656"
       - --bridge-daemon-eth-rpc-endpoint
       - "${ETH_RPC_ENDPOINT}"
       - --dd-error-tracking-format
       - "true"
       - --max-daemon-unhealthy-seconds
       - "4294967295"
    environment:
      # See https://docs.datadoghq.com/profiler/enabling/go/ for DD_ specific environment variables
      - DD_ENV=localnet_${USER}
      - DD_AGENT_HOST=datadog-agent
      - DAEMON_HOME=/nemo-network/chain/.bob
    volumes:
      - ./localnet/nemo-network1:/nemo-network/chain/.bob/data
    ports:
      - "26658:26657"

  nemod2:
    image: local:nemo-network
    entrypoint:
       - cosmovisor
       - run
       - start
       - --log_level
       - error
       - --home
       - /nemo-network/chain/.carl
       - --p2p.persistent_peers
       - "17e5e45691f0d01449c84fd4ae87279578cdd7ec@nemod0:26656,b69182310be02559483e42c77b7b104352713166@nemod1:26656,47539956aaa8e624e0f1d926040e54908ad0eb44@nemod2:26656,5882428984d83b03d0c907c1f0af343534987052@nemod3:26656"
       - --bridge-daemon-eth-rpc-endpoint
       - "${ETH_RPC_ENDPOINT}"
       - --dd-error-tracking-format
       - "true"
       - --max-daemon-unhealthy-seconds
       - "4294967295"
    environment:
      # See https://docs.datadoghq.com/profiler/enabling/go/ for DD_ specific environment variables
      - DD_ENV=localnet_${USER}
      - DD_AGENT_HOST=datadog-agent
      - DAEMON_HOME=/nemo-network/chain/.carl
    volumes:
      - ./localnet/nemo-network2:/nemo-network/chain/.carl/data

  nemod3:
    image: local:nemo-network
    entrypoint:
       - cosmovisor
       - run
       - start
       - --log_level
       - error
       - --home
       - /nemo-network/chain/.dave
       - --p2p.persistent_peers
       - "17e5e45691f0d01449c84fd4ae87279578cdd7ec@nemod0:26656,b69182310be02559483e42c77b7b104352713166@nemod1:26656,47539956aaa8e624e0f1d926040e54908ad0eb44@nemod2:26656,5882428984d83b03d0c907c1f0af343534987052@nemod3:26656"
       - --bridge-daemon-eth-rpc-endpoint
       - "${ETH_RPC_ENDPOINT}"
       - --dd-error-tracking-format
       - "true"
       - --max-daemon-unhealthy-seconds
       - "4294967295"
    environment:
      # See https://docs.datadoghq.com/profiler/enabling/go/ for DD_ specific environment variables
      - DD_ENV=localnet_${USER}
      - DD_AGENT_HOST=datadog-agent
      - DAEMON_HOME=/nemo-network/chain/.dave
    volumes:
      - ./localnet/nemo-network3:/nemo-network/chain/.dave/data
  slinky0:
    image: ghcr.io/skip-mev/slinky-sidecar:v1.0.10
    entrypoint: >
      sh -c "slinky --marketmap-provider dydx_migration_api --oracle-config /etc/slinky/oracle.json --log-std-out-level error"
    environment:
      - SLINKY_CONFIG_PROVIDERS_RAYDIUM_API_API_ENDPOINTS_0_URL=${RAYDIUM_URL}
      - SLINKY_CONFIG_PROVIDERS_UNISWAPV3_API-BASE_API_ENDPOINTS_0_URL=${UNISWAPV3_BASE_URL}
      - SLINKY_CONFIG_PROVIDERS_UNISWAPV3_API-ETHEREUM_API_ENDPOINTS_0_URL=${UNISWAPV3_ETHEREUM_URL}
    volumes:
      - ./contrib/slinky:/etc/slinky
    ports:
      - "8080:8080"
      - "8002:8002" # metrics
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./contrib/prometheus:/etc/prometheus/
    ports:
      - "9091:9090"
  datadog-agent:
    image: public.ecr.aws/datadog/agent:7
    environment:
      # See https://docs.datadoghq.com/containers/docker/?tab=standard#environment-variables for agent configuration
      - DD_API_KEY=${DD_API_KEY}
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "8125:8215"
      - "8126:8126"
